apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.host }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.host }}
  issuerRef:
    name: letsencrypt-{{ .Values.ingress.env }}
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }}
