apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.server.port }}
      name: server
      targetPort: server
      protocol: TCP
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}
